### ISSUE TITLE
I can't find my bus with this app!

### ISSUE THREAD

**Issue by christensenemc** [luqmaan/MetroRappid-iOS#2]
It appears Tampa Florida is not supported by this app.  Is this a bug or is this intentional?

**Comment by luqmaan** [comment]
Dear Kind Sir,

Thank you for your insightful feedback.

Tampa's bus system has a much more advanced API/realtime system called OneBusAway.

HART's implementation of OneBusAway has realtime tracking for all routes, not just the MetroRapid.

For more information about OneBusAway please visit http://tampa.onebusaway.org/.

Have a great day.
